@extends('rebranded.layouts.app')

@section('title', 'Terms')

@section('content')
<div class="text-based-page">
    <div>
        <h2>Terms &amp; Conditions</h2>
    	<p>Last updated: April 23, 2019</p>
        <p>These Terms and Conditions (these “Terms”) govern your access to and use of the website located at endorsify.co (the “Website”) and related service (the “Service”). By accessing and using the Website and the Service, you indicate your unconditional acceptance of the Terms and our <a href="/pages/privacy-and-policy">Privacy Policy</a> on your own behalf and on behalf of any organization you represent (collectively, “you” or “your”).</p>
        <p>Please read these Terms carefully, as they may have changed since your last visit. We reserve the right to change these Terms from time to time for any reason, which shall be effected by posting the updated terms to endorsify.co, provided that such changes shall not apply to any fee-bearing subscriptions to the Services which are then in effect until the expiration or termination of such subscription.</p>
        <h3>Our Service and License to You</h3>
        <p>Endorsify provides an influencer marketing platform focused on pricing content creator advertising space. Endorsify also helps connect brands to influencers seeking to launch campaigns on the Endorsify platform (the “Platform”). Subject to these Terms and our policies, we grant you a limited, non-exclusive, non-transferable, and revocable license to use our Service.</p>
        <h3>Accounts</h3>
        <p>When you create an account with us (your “Account”), you guarantee that you are above the age of 18 and that the information you provide to us is accurate, complete, and current at all times. Inaccurate, incomplete, or obsolete information may result in the immediate termination of your Account in Endorsify’s sole discretion.</p>
        <p>You are responsible for maintaining the confidentiality of your Account and password, including but not limited to the restriction of access to your device and/or Account. You agree to accept responsibility for any and all activities or actions that occur under your Account and/or password, whether your password is with our Service or a third-party service. You further agree to notify us immediately by email at info@endorsify.co of any breach of security or unauthorized use of your Account. Endorsify is not responsible for any loss that you may incur as a result of any unauthorized person using your account or your password.</p>
        <h3>User Content</h3>
        <p>Any Content you create or own, or to which you have a license, and use on the Website or in connection with the Service is your User Content.  In sharing your User Content in connection with the Service or on the Endorsify platform (the “Platform”), you represent and warrant that you have the legal right to use your User Content and grant Endorsify an irrevocable, royalty-free, fully paid up, worldwide, non-exclusive license to use your User Content in providing any Service. The Service may also provide you with features like photo thumbnails, sharing, and searching. These and other features may require us to access, store, and scan your User Content. Your User Content may be searched and viewed by other users, so please think carefully about what you share.  </p>
        <p>You agree to only upload or link content and information that does not violate the law or anyone else’s rights, including intellectual property rights. You represent and warrant that all information posted or shared on your Account is truthful. </p>
        <p>You further agree that we may access, store, process and use any information and personal data that you provide in accordance with our <a href="/pages/privacy-and-policy">Privacy Policy.</a></p>
        <h3>Prohibited Uses</h3>
        <p>You agree that you will not:</p>
        <ul>
            <li>Use this Website or the Service in any way that violates any applicable federal, state, local, or international law or regulation (including, without limitation, any laws regarding the export of data or software to and from the US or other countries);</li>
            <li>Engage in any other conduct that restricts or inhibits anyone’s use or enjoyment of the Website or Service, or which, as determined by us, may harm Endorsify or users of the Website or Service, or expose them to liability;</li>
            <li>Attempt to gain unauthorized access to any Endorsify account, computer systems or networks associated with Endorsify or the Service;</li>
            <li>Upload, post, email, transmit or otherwise make available any content, or initiate communication, that infringes upon someone else’s rights, including patents, trademarks, trade secrets, copyrights or other proprietary rights;</li>
            <li>Upload, post, email, transmit or otherwise make available any content, or initiate communication, that is threatening, offensive, abusive, pornographic, defamatory, or obscene; </li>
            <li>Bully, intimidate, stalk, or harass another Endorsify user for any reason;</li>
            <li>Attempt to create accounts or access or collect information in any way that violates these Terms;</li>
            <li>Use any robot, spider, or other automatic device, process or means to access the Website for any purpose, including monitoring or copying any of the material on the Website;</li>
            <li>Introduce any viruses, Trojan horses, worms, logic bombs, or other material, which are malicious or technologically harmful; </li>
            <li>Impersonate or attempt to impersonate Endorsify, an Endorsify employee, another user, or any other person or entity; or</li>
            <li>Interfere with or disrupt Endorsify’s servers or any networks connected to Endorsify, or disobey any requirements, procedures, policies or regulations of networks connected to Endorsify.</li>
        </ul>
        <h3>Content Removal; Discontinuation of Service</h3>
        <p>We may remove your User Content, or suspend or terminate your Account, if we believe it violates these Terms, any policies posted on our Website, or we are permitted to do so by law. We may change, suspend, or end any Service in our sole discretion. To the extent allowed under law, these changes may be effective upon notice provided to you.</p>
        <h3>Intellectual Property Rights</h3>
        <p>Contents. The contents of the Website and the Platform, including, without limitation, its “look and feel” (e.g., text, graphics, images, logos and button icons), photographs, editorial content, notices, software (including, without limitation, html-based computer programs), trademarks, trade names and/or service marks, and all materials incorporated herein are protected under both United States and other applicable copyright, trademark and intellectual property laws. The contents of the Endorsify Website and Service belong or are licensed to Endorsify or its software or content suppliers. Endorsify grants you the right to view and use the Endorsify Website and Service subject to these Terms. Any distribution, reprint or electronic reproduction of any content from the Endorsify Website or Service in whole or in part for any other purpose is expressly prohibited without our prior written consent.</p>
        <p>Feedback.  While we welcome your feedback, ideas, and suggestions, it is important to be aware of the following restrictions. If you send us feedback, ideas, or suggestions (collectively, “Unsolicited Ideas”), you agree that: (1) your Unsolicited Ideas become the property of Endorsify and you are not owed any compensation in exchange; (2) none of the Unsolicited Ideas contain confidential or proprietary information of any third party; (3) Endorsify may use or redistribute Unsolicited Ideas for any purpose and in any way; (4) there is no obligation for Endorsify to review your Unsolicited Ideas; and (5) Endorsify has no obligation to keep any Unsolicited Ideas confidential.</p>
        <h3>Copyrights on Endorsify</h3>
        <p>Endorsify does not permit copyright infringing activities to occur on this Website or on our Platform and may remove any content of any kind, for example, if properly informed that certain content infringes upon another’s copyright rights. </p>
        <p>Endorsify follows the Digital Millennium Copyright Act, which is available at <a href="https://www.copyright.gov/legislation/dmca.pdf">https://www.copyright.gov/legislation/dmca.pdf</a>. </p>
        <p>If you are a copyright owner or an agent thereof and believe that any content on this Website or our Platform infringes upon your copyrights, you may notify us by providing the following information in writing:</p>
        <ul>
            <li>A physical or electronic signature of a person authorized to act on behalf of the owner of an exclusive copyright right that is allegedly infringed;</li>
            <li>Identification of the location where the original or an authorized copy of the copyrighted work exists;</li>
            <li>Identification of the material that is claimed to be infringing and a description of the infringing activity and information reasonably sufficient to permit Endorsify to locate the same;</li>
            <li>Information reasonably sufficient to permit Endorsify to contact you, such as an address, telephone number, and, if available, an email address;</li>
            <li>A statement that you have a good faith belief that use of the material in the manner complained of is not authorized by the copyright owner, its agent, or the law; and</li>
            <li>A statement that the information in the notification is accurate, and, under penalty of perjury, that you are authorized to act on behalf of the owner of an exclusive copyright right that is allegedly infringed.</li>
        </ul>
        <p>Upon receipt of a DMCA notice, Endorsify may take whatever action we think is appropriate, determined in our sole discretion, which may include removal of the reported content. If we remove content, we may notify the user who shared the content to provide an opportunity to send counter-notice.</p>
        <p>Our contact for notice of claims of copyright infringement can be reached as follows:</p>
        <p>Endorsify Copyright Agent <br>
        8605 Santa Monica Blvd., #46442 <br>
        Los Angeles, CA 90068
        </p>
        <p>You acknowledge that if you fail to comply with all of the requirements above, your notice may not be valid. Please note that under Section 512(f) of the DMCA, any person who knowingly materially misrepresents that material or activity is infringing may be subject to liability.</p>
        <h3>Fees and Payment</h3>
        <p>To use the Service, you must have Internet access and an Endorsify-ready device, and provide us with a current, valid, accepted method of payment (your “Payment Method”). By using the Service, you accept the subscription fee (the “Subscription Fee”) and authorize Ensorsify to process your payment using your Payment Method. </p>
        <p>Your Endorsify subscription may start with a free trial (a “Trial Subscription”). Trial Subscriptions are available only to new Endorsify users, unless otherwise specified in Endorsify’s sole discretion. We may limit Trial Subscription eligibility or duration, or revoke a Trial Subscription, if we determine that you are not eligible. The Trial Subscription period lasts for 3 days, or so long as otherwise specified when you create your Account (the “Trial Period”). When signing up for a Trial Subscription, you may be required to provide a Payment Method, which will not be charged a Subscription Fee before the end of the Trial Period. If you do not cancel your Trial Subscription before the end of the Trial Period, the Subscription Fee for the subscription duration you have selected will be processed and your subscription will automatically renew in accordance with the subscription duration selected.</p>
        <p>The Subscription Fee will be charged on an annual basis to your Payment Method on the calendar day corresponding to the commencement of the paying portion of your subscription until you cancel your subscription in advance of the subscription renewal date. Your payment date may change in some circumstances, for example if your Payment Method has not successfully settled or if your subscription began on a day not contained in a given month. </p>
        <p>Fees for the Service are subject to change at Endorsify’s sole discretion upon 30 days’ notice from Endorsify (the “Notice Period”). This notice may be posted on the Website or may appear with the Service itself. Subscription Fee changes will take effect at the start of the next subscription period following the date of the Subscription Fee change. If you do not accept the new fee, you may cancel your Account during the Notice Period by providing notice of your intent to cancel via email to info@endorsify.co. By continuing to use the Service after the effective date of a fee change, you thereby agree to such change.</p>
        <p>Payments are not refundable. Endorsify will not issue any refunds for Accounts that are cancelled mid-subscription period. Payments are made for the upcoming billing cycle. Endorsify does not provide pro-rated refunds for Endorsify accounts that are cancelled during their subscription period. </p>
        <p>Endorsify shall not be liable to you or to any third party for any modifications to the Service or prices.</p>
        <h3>Links to Other Websites</h3>
        <p>Our Service may contain links to third party web sites or resources provided by third parties, which are provided for your convenience only. Endorsify LLC has no control over the content, privacy policies, or practices of any third party web sites or services, and Endorsify accepts no responsibility for any loss or damage that may arise from your use of them, directly or indirectly. If you decide to access any of the third party websites or content, you do so entirely at your own risk. </p>
        <p>Links to third party websites or content on this Website do not in any way imply Endorsify’s endorsements of such third party products or services, and these Terms in no way create any legal relationship between you and the provider of such third party content. Endorsify shall have the right to block links to this Website or the Service at any time without prior notice.</p>
        <h3>Termination</h3>
        <p>You are solely responsible for properly closing your Account. You may terminate your Account at any time by emailing us at info@endorsify.co before the billing date of your next subscription period.</p>
        <p>We may terminate or suspend your Account and bar access to the Service or your Account immediately, without prior notice or liability, in our sole discretion, for any reason whatsoever, including but not limited to a breach of the Terms.</p>
        <p>All provisions of the Terms which by their nature should survive termination shall survive termination, including, without limitation, ownership provisions, warranty disclaimers, indemnity and limitations of liability.</p>
        <h3>Governing Law</h3>
        <p>These Terms shall be governed and construed in accordance with the laws of California, United States, without regard to its conflict of law provisions.</p>
        <h3>Changes to these Terms</h3>
        <p>We reserve the right, at our sole discretion, to modify or replace these Terms at any time. If a revision is material, we will provide at least 30 days’ notice prior to any new terms taking effect. What constitutes a material change will be determined at our sole discretion.</p>
        <p>By continuing to access or use our Service after any revisions become effective, you agree to be bound by the revised terms. If you do not agree to the new terms, you are no longer authorized to use the Service.</p>
        <h3>Disclaimer Regarding Use of Mobile Device</h3>
        <p>Use of the Website and Service may be available through a compatible mobile device, internet and/or network access and may require software. You agree that you are solely responsible for these requirements, including any applicable changes, updates and fees, as well as the terms of your agreement with your mobile device and telecommunications provider. WE MAKE NO WARRANTIES OF ANY KIND, EXPRESS, STATUTORY, OR IMPLIED, AS TO: (i) THE AVAILABILITY OF TELECOMMUNICATION SERVICES FROM YOUR PROVIDER AND ACCESS TO THE SERVICES AT ANY TIME OR FROM ANY LOCATION; (ii) ANY LOSS, DAMAGE, OR OTHER SECURITY INTRUSION OF THE TELECOMMUNICATION SERVICES; AND (iii) ANY DISCLOSURE OF INFORMATION TO THIRD PARTIES OR FAILURE TO TRANSMIT ANY DATA, COMMUNICATIONS OR SETTINGS CONNECTED WITH THE SERVICES.	</p>
        <h3>Disclaimer of Representations and Warranties</h3>
        <p>THE WEBSITE, SERVICE, AND ANY MATERIALS MADE AVAILABLE THROUGH OR IN CONNECTION WITH THE WEBSITE AND SERVICE ARE PROVIDED TO YOU “AS IS” WITHOUT ANY WARRANTIES OF ANY KIND, WHETHER EXPRESS, IMPLIED, OR STATUTORY. YOU AGREE THAT YOU MUST BEAR ALL RISK ASSOCIATED WITH THE USE OF THE WEBSITE AND SERVICE. NEITHER WE NOR ANY THIRD PARTY PARTNERS PROVIDE ANY WARRANTY OR GUARANTY AS TO THE ACCURACY, TIMELINESS, PERFORMANCE, COMPLETENESS OR SUITABILITY OF THE INFORMATION AND MATERIALS FOUND OR OFFERED ON THIS WEBSITE FOR ANY PARTICULAR PURPOSE. YOU ACKNOWLEDGE THAT SUCH INFORMATION AND MATERIALS MAY CONTAIN INACCURACIES OR ERRORS AND WE EXPRESSLY EXCLUDE LIABILITY FOR ANY SUCH INACCURACIES OR ERRORS TO THE FULLEST EXTENT POSSIBLE BY LAW. NEITHER ENDORSIFY NOR ANY OF ITS THIRD PARTY PARTNERS REPRESENT, WARRANT, OR COVENANT THAT THE WEBSITE WILL BE SECURE, UNINTERRUPTED, OR ERROR FREE. ENDORSIFY FURTHER MAKES NO WARRANTY THAT THE WEBSITE WILL BE FREE OF VIRUSES, WORMS OR TROJAN HORSES OR THAT IT WILL FUNCTION OR OPERATE IN CONJUNCTION WITH ANY OTHER PRODUCT OR SOFTWARE. YOU EXPRESSLY AGREE THAT USE OF THE WEBSITE, MOBILE APP, AND SERVICES IS AT YOUR SOLE RISK AND THAT ENDORSIFY, ITS AFFILIATES, AND THEIR THIRD PARTY PARTNERS SHALL NOT BE RESPONSIBLE FOR ANY TERMINATION, INTERRUPTION OF SERVICES, DELAYS, ERRORS, FAILURES OF PERFORMANCE, DEFECTS, LINE FAILURES, OR OMISSIONS ASSOCIATED WITH THE WEBSITE OR YOUR USE THEREOF. YOUR SOLE REMEDY AGAINST ENDORSIFY FOR DISSATISFACTION WITH THE WEBSITE, MOBILE APP, SERVICES OR THE CONTENT THEREIN IS TO CEASE YOUR USE OF THE WEBSITE AND/OR THE CONTENT.</p>
        <h3>Limitation of Liability</h3>
        <p>ENDORSIFY SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, CONSEQUENTIAL, SPECIAL, EXEMPLARY OR PUNITIVE DAMAGES OF ANY KIND, UNDER ANY CONTRACT, NEGLIGENCE, STRICT LIABILITY OR OTHER THEORY, INCLUDING WITHOUT LIMITATION, DAMAGES FOR LOSS OF PROFITS, USE, DATA, LOSS OF OTHER INTANGIBLES, LOSS OF SECURITY OF INFORMATION YOU HAVE PROVIDED IN CONNECTION WITH YOUR USE OF THE WEBSITE OR SERVICES, OR UNAUTHORIZED INTERCEPTION OF ANY SUCH INFORMATION BY THIRD PARTIES, EVEN IF ADVISED IN ADVANCE OF SUCH DAMAGES OR LOSSES. IN PARTICULAR, AND WITHOUT LIMITATION, ENDORSIFY WILL NOT BE LIABLE FOR DAMAGES OF ANY KIND RESULTING FROM YOUR ACCESS TO OR USE OF, OR INABILITY TO ACCESS OR USE, THE WEBSITE OR SERVICE, OR FROM ANY CONTENT POSTED ON THE WEBSITE OR PLATFORM, OR IN CONNECTION WITH THE SERVICE.  YOUR SOLE AND EXCLUSIVE REMEDY FOR DISSATISFACTION WITH WEBSITE OR SERVICE IS TO STOP USING WEBSITE OR SERVICE.  THE MAXIMUM LIABILITY OF ENDORSIFY FOR ALL DAMAGES, LOSSES AND CAUSES OF ACTION, WHETHER IN CONTRACT, TORT (INCLUDING WITHOUT LIMITATION NEGLIGENCE) OR OTHERWISE, SHALL BE THE TOTAL AMOUNT, IF ANY, PAID BY YOU TO ENDORSIFY TO ACCESS AND USE THE WEBSITE AND SERVICE.</p>
        <h3>Indemnification</h3>
        <p>BY ACCEPTING THESE TERMS OF USE, YOU AGREE TO INDEMNIFY AND OTHERWISE HOLD HARMLESS ENDORSIFY, INC., EACH OF ITS AFFILIATES AND EACH OF ITS RESPECTIVE OFFICERS, DIRECTORS, EMPLOYEES, AGENTS, PARTNERS AND REPRESENTATIVES FROM ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, PUNITIVE OR EXEMPLARY DAMAGES ARISING OR RESULTING FROM (I) YOUR USE OR MISUSE OF THE ENDORSIFY WEBSITE, PLATFORM OR SERVICE OR (II) ANY BREACH OR ALLEGED BREACH OF THESE TERMS OF USE BY YOU.</p>
        <h3>Other</h3>
        <p>Our failure to enforce any right or provision of these Terms will not be considered a waiver of those rights. </p>
        <p>If any provision of these Terms is held to be invalid or unenforceable by a court, the remaining provisions of these Terms will remain in full effect. </p>
        <p>These Terms constitute the entire agreement between us regarding our Service, and supersede and replace any prior agreements we might have had between us regarding the Service.</p>
        <p>We reserve all rights not expressly granted to you.</p>
        <h3>Contact Us</h3>
    	<p>If you have any questions about these Terms, please contact us at info@endorsify.co</p>
    	<div class="logo-tk" style="margin-top: 50px; margin-bottom: 15px;">
    		<img src="https://endorsify.co/frontend/img/logo_blue.png" alt="Endorsify" style="height: 50px;">
    	</div>
    	<p style="padding: 0;">Thanks,</p>
    	<p style="font-size: 16px; margin-bottom: 20px;">The Endorsify Team</p>
    </div>
    <footer></footer>
</div>

@endsection
